name: "Feedback"
description: Report inaccurate data, suggest improvements, or share your thoughts
title: "[Feedback] "
labels: ["feedback"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Feedback type
      options:
        - Data accuracy issue
        - Missing causal factor
        - Source is outdated or broken
        - Design / UX suggestion
        - General feedback
    validations:
      required: true
  - type: input
    id: chart
    attributes:
      label: Which chart? (if applicable)
      placeholder: "e.g. Wage-Productivity Gap"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe your feedback
      description: Be as specific as possible. If reporting a data issue, include the correct value and source.
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Supporting source (if applicable)
      placeholder: "https://..."
    validations:
      required: false
